// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jugorqxbinrgtywbsjcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1Z29ycXhiaW5yZ3R5d2JzamNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mzg1MjAsImV4cCI6MjA3NDAxNDUyMH0.o9h3DXdR6xrDbaomg6IykpfBUkoDy1ddj-pxoPUmERs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});